### ISSUE TITLE
Publishing matches 0.2

### ISSUE THREAD

**Issue by bluss** [SimonSapin/rust-std-candidates#11]
It would be cool to have the updated docs & implementation of the matches crate published. Thank you in advance.

**Comment by SimonSapin** [comment]
Sure! What makes it a breaking change, though?

**Comment by bluss** [comment]
Two minor things:

- Remove the tt helper macro from public API
- Increased minimum required Rust version to 1.12

**Comment by SimonSapin** [comment]
Although `_matches_tt_as_expr_hack` was exported because `macro_rules` doesn’t support privacy hygiene, I consider it wasn’t part of the public API. I used the underscore prefix convention from Python out of habit, though maybe that convention isn’t established in Rust.

As to increasing the minimum language version, I don’t know if we should consider that a breaking change. @nox, do you have an opinion?

**Comment by SimonSapin** [comment]
I’ve reverted the `_matches_tt_as_expr_hack` change and published https://crates.io/crates/matches/0.1.6. Slightly uglier code is less of a bother than going through reverse dependencies to deal with a breaking version change.

**Comment by bluss** [comment]
It's not a simple choice (major version friction exists) but I have lately stuck to bumping Rust version only in breaking version upgrades, at least as far as it has been known.
